language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: python setup.py install
script: python tests/test_it_all.py
branches:
  only:
    - master
